// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7ma2YzAhoCqIW-TIAAk0tM7C-OBUYpg',
    appId: '1:185840232162:web:820c876632c91e2d6120bb',
    messagingSenderId: '185840232162',
    projectId: 'formfireba',
    authDomain: 'formfireba.firebaseapp.com',
    databaseURL: 'https://formfireba-default-rtdb.firebaseio.com',
    storageBucket: 'formfireba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKyc-3cBbvY6MD-RVlO0cF7mNqWm3ais',
    appId: '1:185840232162:android:4007a3677c11f7f46120bb',
    messagingSenderId: '185840232162',
    projectId: 'formfireba',
    databaseURL: 'https://formfireba-default-rtdb.firebaseio.com',
    storageBucket: 'formfireba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRBWngfxW4kXzoxpXEzIw5TYLqbjBOM8',
    appId: '1:185840232162:ios:beb392a33d1b3f836120bb',
    messagingSenderId: '185840232162',
    projectId: 'formfireba',
    databaseURL: 'https://formfireba-default-rtdb.firebaseio.com',
    storageBucket: 'formfireba.appspot.com',
    iosBundleId: 'com.example.firebasenoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRBWngfxW4kXzoxpXEzIw5TYLqbjBOM8',
    appId: '1:185840232162:ios:2184f890dfac110a6120bb',
    messagingSenderId: '185840232162',
    projectId: 'formfireba',
    databaseURL: 'https://formfireba-default-rtdb.firebaseio.com',
    storageBucket: 'formfireba.appspot.com',
    iosBundleId: 'com.example.firebasenoteapp.RunnerTests',
  );
}
